# build requirement config2cmd (https://github.com/ShihHsuanChen/cmd_config)
# build dist:  config2cmd build-compose.yml -e env.cfg --run build
# build setup: config2cmd build-compose.yml -e env.cfg --run build_setup

commands:
    build:
        executable: pyinstaller
        equalstr: False
        positional:
            - "--add-data templates/*;./templates/"
            - main.py

    build_setup:
        executable: iscc
        positional:
            - build_setup.iss
